language: android
jdk: oraclejdk8
sudo: false

env:
    global:
        - ADB_INSTALL_TIMEOUT=10    #Time out to 10 mins

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:      #Cache all dirs under .gradle folder
    - $HOME/.gradle/daemon      #Cache daemon logs
    - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
    - $HOME/.gradle/wrapper     #Cache the gradle

android:
    update_sdk: true
    components:
        - platform-tools
        - tools
        - tools
        - build-tools-25.0.2
        - android-21
        - android-25

        # Additional components
        - extra-android-m2repository

        #system images
        - sys-img-armeabi-v7a-android-21

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

notifications:
    email:
        on_success: never
        on_failure: always

before_script:
    - cd Aviato
    - chmod +x gradlew      #Grant permissions
    - android list targets
    - echo no | android create avd --force --name test --target android-21 --abi armeabi-v7a    #Create AVD for given api
    - emulator -avd test -no-skin -no-audio -no-window &    #Start emulator

before_install:
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
    - android-wait-for-emulator
    - adb devices   #Display list of devices
    - adb shell input keyevent 82 &
    - ./gradlew connectedCheck -PdisablePreDex --stacktrace
